import sys
import webbrowser
from random import randint
# a.upper()
# a.title()
try:
    print('''
.---------------------------------------------------------------.
|       ___________             ________                        |
|       \__    ___/___   ____  /  _____/  ____   ____           |
|         |    |_/ __ \ /    \/   \  ____/ __ \ /    \          |
|         |    |\  ___/|   |  \    \_\  \  ___/|   |  \         |
|         |____| \___  >___|  /\______  /\___  >___|  /         |
|                    \/     \/        \/     \/     \/          |
|                                                               |
|                                     Made by _t0x1c            |
|                                       ( Filip )               |
.---------------------------------------------------------------.
''')

    name_file = raw_input("Name of victim: ")
    cmp_kata = open(name_file + '.txt','a+')
    print ('[+] Here you can enter info and words about the victim. You might want to include things such as their name and relatives.')
    a = raw_input('Info 1 : ')
    b = raw_input('Info 2 : ')
    c = raw_input('Info 3 : ')
    d = raw_input('Info 4 : ')
    e = raw_input('Info 5 : ')
    f = raw_input('Info 6 : ')
    g = raw_input('Info 7 : ')
    h = raw_input('Info 8 : ')
    i = raw_input('Info 9 : ')
    j = raw_input('Info 10 : ')
    birthday = raw_input("Birthday (DDMMYYYY): ")
    while len(birthday) != 0 and len(birthday) != 8:
	    print "\n[-] You must enter 8 digits for a birthday!"
	    birthday = raw_input("Birthday (DDMMYYYY): ")
    birthday = str(birthday)
    ### The real painful shit starts here ###
    cmp_kata.write(a)
    cmp_kata.write('\n')
    cmp_kata.write(b)
    cmp_kata.write('\n')
    cmp_kata.write(c)
    cmp_kata.write('\n')
    cmp_kata.write(d)
    cmp_kata.write('\n')
    cmp_kata.write(e)
    cmp_kata.write('\n')
    cmp_kata.write(f)
    cmp_kata.write('\n')
    cmp_kata.write(g)
    cmp_kata.write('\n')
    cmp_kata.write(h)
    cmp_kata.write('\n')
    cmp_kata.write(i)
    cmp_kata.write('\n')
    cmp_kata.write(j)
    cmp_kata.write(birthday + name_file)
    cmp_kata.write('\n')
    cmp_kata.write(name_file.title() + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(name_file + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(birthday)
    cmp_kata.write('\n')
    cmp_kata.write(name_file)
    cmp_kata.write('\n')
    cmp_kata.write(a + a)
    cmp_kata.write('\n')
    cmp_kata.write(a + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + c)
    cmp_kata.write('\n')
    cmp_kata.write(a + d)
    cmp_kata.write('\n')
    cmp_kata.write(a + e)
    cmp_kata.write('\n')
    cmp_kata.write(a + f)
    cmp_kata.write('\n')
    cmp_kata.write(a + g)
    cmp_kata.write('\n')
    cmp_kata.write(a + h)
    cmp_kata.write('\n')
    cmp_kata.write(a + i)
    cmp_kata.write('\n')
    cmp_kata.write(a + j)
    cmp_kata.write('\n')
    cmp_kata.write(b + a)
    cmp_kata.write('\n')
    cmp_kata.write(b + b)
    cmp_kata.write('\n')
    cmp_kata.write(b + c)
    cmp_kata.write('\n')
    cmp_kata.write(b + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + e)
    cmp_kata.write('\n')
    cmp_kata.write(b + f)
    cmp_kata.write('\n')
    cmp_kata.write(b + g)
    cmp_kata.write('\n')
    cmp_kata.write(b + h)
    cmp_kata.write('\n')
    cmp_kata.write(b + i)
    cmp_kata.write('\n')
    cmp_kata.write(b + j)
    cmp_kata.write('\n')
    cmp_kata.write(c + a)
    cmp_kata.write('\n')
    cmp_kata.write(c + b)
    cmp_kata.write('\n')
    cmp_kata.write(c + c)
    cmp_kata.write('\n')
    cmp_kata.write(c + d)
    cmp_kata.write('\n')
    cmp_kata.write(c + e)
    cmp_kata.write('\n')
    cmp_kata.write(c + f)
    cmp_kata.write('\n')
    cmp_kata.write(c + g)
    cmp_kata.write('\n')
    cmp_kata.write(c + h)
    cmp_kata.write('\n')
    cmp_kata.write(c + i)
    cmp_kata.write('\n')
    cmp_kata.write(c + j)
    cmp_kata.write('\n')
    cmp_kata.write(d + a)
    cmp_kata.write('\n')
    cmp_kata.write(d + b)
    cmp_kata.write('\n')
    cmp_kata.write(d + c)
    cmp_kata.write('\n')
    cmp_kata.write(d + d)
    cmp_kata.write('\n')
    cmp_kata.write(d + e)
    cmp_kata.write('\n')
    cmp_kata.write(d + f)
    cmp_kata.write('\n')
    cmp_kata.write(d + g)
    cmp_kata.write('\n')
    cmp_kata.write(d + h)
    cmp_kata.write('\n')
    cmp_kata.write(d + i)
    cmp_kata.write('\n')
    cmp_kata.write(d + j)
    cmp_kata.write('\n')
    cmp_kata.write(e + a)
    cmp_kata.write('\n')
    cmp_kata.write(e + b)
    cmp_kata.write('\n')
    cmp_kata.write(e + c)
    cmp_kata.write('\n')
    cmp_kata.write(e + d)
    cmp_kata.write('\n')
    cmp_kata.write(e + e)
    cmp_kata.write('\n')
    cmp_kata.write(e + f)
    cmp_kata.write('\n')
    cmp_kata.write(e + g)
    cmp_kata.write('\n')
    cmp_kata.write(e + h)
    cmp_kata.write('\n')
    cmp_kata.write(e + i)
    cmp_kata.write('\n')
    cmp_kata.write(e + j)
    cmp_kata.write('\n')
    cmp_kata.write(f + a)
    cmp_kata.write('\n')
    cmp_kata.write(f + b)
    cmp_kata.write('\n')
    cmp_kata.write(f + c)
    cmp_kata.write('\n')
    cmp_kata.write(f + d)
    cmp_kata.write('\n')
    cmp_kata.write(f + e)
    cmp_kata.write('\n')
    cmp_kata.write(f + f)
    cmp_kata.write('\n')
    cmp_kata.write(f + g)
    cmp_kata.write('\n')
    cmp_kata.write(f + h)
    cmp_kata.write('\n')
    cmp_kata.write(f + i)
    cmp_kata.write('\n')
    cmp_kata.write(f + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + a)
    cmp_kata.write('\n')
    cmp_kata.write(g + b)
    cmp_kata.write('\n')
    cmp_kata.write(g + c)
    cmp_kata.write('\n')
    cmp_kata.write(g + d)
    cmp_kata.write('\n')
    cmp_kata.write(g + e)
    cmp_kata.write('\n')
    cmp_kata.write(g + f)
    cmp_kata.write('\n')
    cmp_kata.write(g + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + h)
    cmp_kata.write('\n')
    cmp_kata.write(g + i)
    cmp_kata.write('\n')
    cmp_kata.write(g + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + a)
    cmp_kata.write('\n')
    cmp_kata.write(h + b)
    cmp_kata.write('\n')
    cmp_kata.write(h + c)
    cmp_kata.write('\n')
    cmp_kata.write(h + d)
    cmp_kata.write('\n')
    cmp_kata.write(h + e)
    cmp_kata.write('\n')
    cmp_kata.write(h + f)
    cmp_kata.write('\n')
    cmp_kata.write(h + g)
    cmp_kata.write('\n')
    cmp_kata.write(h + h)
    cmp_kata.write('\n')
    cmp_kata.write(h + i)
    cmp_kata.write('\n')
    cmp_kata.write(h + j)
    cmp_kata.write('\n')
    cmp_kata.write(i + a)
    cmp_kata.write('\n')
    cmp_kata.write(i + b)
    cmp_kata.write('\n')
    cmp_kata.write(i + c)
    cmp_kata.write('\n')
    cmp_kata.write(i + d)
    cmp_kata.write('\n')
    cmp_kata.write(i + e)
    cmp_kata.write('\n')
    cmp_kata.write(i + f)
    cmp_kata.write('\n')
    cmp_kata.write(i + g)
    cmp_kata.write('\n')
    cmp_kata.write(i + h)
    cmp_kata.write('\n')
    cmp_kata.write(i + i)
    cmp_kata.write('\n')
    cmp_kata.write(i + j)
    cmp_kata.write('\n')
    cmp_kata.write(j + a)
    cmp_kata.write('\n')
    cmp_kata.write(j + b)
    cmp_kata.write('\n')
    cmp_kata.write(j + c)
    cmp_kata.write('\n')
    cmp_kata.write(j + d)
    cmp_kata.write('\n')
    cmp_kata.write(j + e)
    cmp_kata.write('\n')
    cmp_kata.write(j + f)
    cmp_kata.write('\n')
    cmp_kata.write(j + g)
    cmp_kata.write('\n')
    cmp_kata.write(j + h)
    cmp_kata.write('\n')
    cmp_kata.write(j + i)
    cmp_kata.write('\n')
    cmp_kata.write(j + j)
    cmp_kata.write('\n')
    cmp_kata.write(a + a + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + a + c)
    cmp_kata.write('\n')
    cmp_kata.write(a + a + d)
    cmp_kata.write('\n')
    cmp_kata.write(a + a + e)
    cmp_kata.write('\n')
    cmp_kata.write(a + a + f)
    cmp_kata.write('\n')
    cmp_kata.write(a + a + g)
    cmp_kata.write('\n')
    cmp_kata.write(a + a + h)
    cmp_kata.write('\n')
    cmp_kata.write(a + a + i)
    cmp_kata.write('\n')
    cmp_kata.write(a + a + j)
    cmp_kata.write('\n')
    cmp_kata.write(a + b + a)
    cmp_kata.write('\n')
    cmp_kata.write(a + b + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + b + c)
    cmp_kata.write('\n')
    cmp_kata.write(a + b + d)
    cmp_kata.write('\n')
    cmp_kata.write(a + b + e)
    cmp_kata.write('\n')
    cmp_kata.write(a + b + f)
    cmp_kata.write('\n')
    cmp_kata.write(a + b + g)
    cmp_kata.write('\n')
    cmp_kata.write(a + b + h)
    cmp_kata.write('\n')
    cmp_kata.write(a + b + i)
    cmp_kata.write('\n')
    cmp_kata.write(a + b + j)
    cmp_kata.write('\n')
    cmp_kata.write(a + c + a)
    cmp_kata.write('\n')
    cmp_kata.write(a + c + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + c + c)
    cmp_kata.write('\n')
    cmp_kata.write(a + c + d)
    cmp_kata.write('\n')
    cmp_kata.write(a + c + e)
    cmp_kata.write('\n')
    cmp_kata.write(a + c + f)
    cmp_kata.write('\n')
    cmp_kata.write(a + c + g)
    cmp_kata.write('\n')
    cmp_kata.write(a + c + h)
    cmp_kata.write('\n')
    cmp_kata.write(a + c + i)
    cmp_kata.write('\n')
    cmp_kata.write(a + c + j)
    cmp_kata.write('\n')
    cmp_kata.write(a + d + a)
    cmp_kata.write('\n')
    cmp_kata.write(a + d + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + d + c)
    cmp_kata.write('\n')
    cmp_kata.write(a + d + d)
    cmp_kata.write('\n')
    cmp_kata.write(a + d + e)
    cmp_kata.write('\n')
    cmp_kata.write(a + d + f)
    cmp_kata.write('\n')
    cmp_kata.write(a + d + g)
    cmp_kata.write('\n')
    cmp_kata.write(a + d + h)
    cmp_kata.write('\n')
    cmp_kata.write(a + d + i)
    cmp_kata.write('\n')
    cmp_kata.write(a + d + j)
    cmp_kata.write('\n')
    cmp_kata.write(a + e + a)
    cmp_kata.write('\n')
    cmp_kata.write(a + e + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + e + c)
    cmp_kata.write('\n')
    cmp_kata.write(a + e + d)
    cmp_kata.write('\n')
    cmp_kata.write(a + e + e)
    cmp_kata.write('\n')
    cmp_kata.write(a + e + f)
    cmp_kata.write('\n')
    cmp_kata.write(a + e + g)
    cmp_kata.write('\n')
    cmp_kata.write(a + e + h)
    cmp_kata.write('\n')
    cmp_kata.write(a + e + i)
    cmp_kata.write('\n')
    cmp_kata.write(a + e + j)
    cmp_kata.write('\n')
    cmp_kata.write(a + f + a)
    cmp_kata.write('\n')
    cmp_kata.write(a + f + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + f + c)
    cmp_kata.write('\n')
    cmp_kata.write(a + f + d)
    cmp_kata.write('\n')
    cmp_kata.write(a + f + e)
    cmp_kata.write('\n')
    cmp_kata.write(a + f + f)
    cmp_kata.write('\n')
    cmp_kata.write(a + f + g)
    cmp_kata.write('\n')
    cmp_kata.write(a + f + h)
    cmp_kata.write('\n')
    cmp_kata.write(a + f + i)
    cmp_kata.write('\n')
    cmp_kata.write(a + f + j)
    cmp_kata.write('\n')
    cmp_kata.write(a + g + a)
    cmp_kata.write('\n')
    cmp_kata.write(a + g + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + g + c)
    cmp_kata.write('\n')
    cmp_kata.write(a + g + d)
    cmp_kata.write('\n')
    cmp_kata.write(a + g + e)
    cmp_kata.write('\n')
    cmp_kata.write(a + g + f)
    cmp_kata.write('\n')
    cmp_kata.write(a + g + g)
    cmp_kata.write('\n')
    cmp_kata.write(a + g + h)
    cmp_kata.write('\n')
    cmp_kata.write(a + g + i)
    cmp_kata.write('\n')
    cmp_kata.write(a + g + j)
    cmp_kata.write('\n')
    cmp_kata.write(a + h + a)
    cmp_kata.write('\n')
    cmp_kata.write(a + h + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + h + c)
    cmp_kata.write('\n')
    cmp_kata.write(a + h + d)
    cmp_kata.write('\n')
    cmp_kata.write(a + h + e)
    cmp_kata.write('\n')
    cmp_kata.write(a + h + f)
    cmp_kata.write('\n')
    cmp_kata.write(a + h + g)
    cmp_kata.write('\n')
    cmp_kata.write(a + h + h)
    cmp_kata.write('\n')
    cmp_kata.write(a + h + i)
    cmp_kata.write('\n')
    cmp_kata.write(a + h + j)
    cmp_kata.write('\n')
    cmp_kata.write(a + i + a)
    cmp_kata.write('\n')
    cmp_kata.write(a + i + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + i + c)
    cmp_kata.write('\n')
    cmp_kata.write(a + i + d)
    cmp_kata.write('\n')
    cmp_kata.write(a + i + e)
    cmp_kata.write('\n')
    cmp_kata.write(a + i + f)
    cmp_kata.write('\n')
    cmp_kata.write(a + i + g)
    cmp_kata.write('\n')
    cmp_kata.write(a + i + h)
    cmp_kata.write('\n')
    cmp_kata.write(a + i + i)
    cmp_kata.write('\n')
    cmp_kata.write(a + i + j)
    cmp_kata.write('\n')
    cmp_kata.write(a + j + a)
    cmp_kata.write('\n')
    cmp_kata.write(a + j + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + j + c)
    cmp_kata.write('\n')
    cmp_kata.write(a + j + d)
    cmp_kata.write('\n')
    cmp_kata.write(a + j + e)
    cmp_kata.write('\n')
    cmp_kata.write(a + j + f)
    cmp_kata.write('\n')
    cmp_kata.write(a + j + g)
    cmp_kata.write('\n')
    cmp_kata.write(a + j + h)
    cmp_kata.write('\n')
    cmp_kata.write(a + j + i)
    cmp_kata.write('\n')
    cmp_kata.write(a + j + j)
    cmp_kata.write('\n')
    cmp_kata.write(b + a + b)
    cmp_kata.write('\n')
    cmp_kata.write(b + a + c)
    cmp_kata.write('\n')
    cmp_kata.write(b + a + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + a + e)
    cmp_kata.write('\n')
    cmp_kata.write(b + a + f)
    cmp_kata.write('\n')
    cmp_kata.write(b + a + g)
    cmp_kata.write('\n')
    cmp_kata.write(b + a + h)
    cmp_kata.write('\n')
    cmp_kata.write(b + a + i)
    cmp_kata.write('\n')
    cmp_kata.write(b + a + j)
    cmp_kata.write('\n')
    cmp_kata.write(b + b + a)
    cmp_kata.write('\n')
    cmp_kata.write(b + b + b)
    cmp_kata.write('\n')
    cmp_kata.write(b + b + c)
    cmp_kata.write('\n')
    cmp_kata.write(b + b + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + b + e)
    cmp_kata.write('\n')
    cmp_kata.write(b + b + f)
    cmp_kata.write('\n')
    cmp_kata.write(b + b + g)
    cmp_kata.write('\n')
    cmp_kata.write(b + b + h)
    cmp_kata.write('\n')
    cmp_kata.write(b + b + i)
    cmp_kata.write('\n')
    cmp_kata.write(b + b + j)
    cmp_kata.write('\n')
    cmp_kata.write(b + c + a)
    cmp_kata.write('\n')
    cmp_kata.write(b + c + b)
    cmp_kata.write('\n')
    cmp_kata.write(b + c + c)
    cmp_kata.write('\n')
    cmp_kata.write(b + c + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + c + e)
    cmp_kata.write('\n')
    cmp_kata.write(b + c + f)
    cmp_kata.write('\n')
    cmp_kata.write(b + c + g)
    cmp_kata.write('\n')
    cmp_kata.write(b + c + h)
    cmp_kata.write('\n')
    cmp_kata.write(b + c + i)
    cmp_kata.write('\n')
    cmp_kata.write(b + c + j)
    cmp_kata.write('\n')
    cmp_kata.write(b + d + a)
    cmp_kata.write('\n')
    cmp_kata.write(b + d + b)
    cmp_kata.write('\n')
    cmp_kata.write(b + d + c)
    cmp_kata.write('\n')
    cmp_kata.write(b + d + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + d + e)
    cmp_kata.write('\n')
    cmp_kata.write(b + d + f)
    cmp_kata.write('\n')
    cmp_kata.write(b + d + g)
    cmp_kata.write('\n')
    cmp_kata.write(b + d + h)
    cmp_kata.write('\n')
    cmp_kata.write(b + d + i)
    cmp_kata.write('\n')
    cmp_kata.write(b + d + j)
    cmp_kata.write('\n')
    cmp_kata.write(b + e + a)
    cmp_kata.write('\n')
    cmp_kata.write(b + e + b)
    cmp_kata.write('\n')
    cmp_kata.write(b + e + c)
    cmp_kata.write('\n')
    cmp_kata.write(b + e + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + e + e)
    cmp_kata.write('\n')
    cmp_kata.write(b + e + f)
    cmp_kata.write('\n')
    cmp_kata.write(b + e + g)
    cmp_kata.write('\n')
    cmp_kata.write(b + e + h)
    cmp_kata.write('\n')
    cmp_kata.write(b + e + i)
    cmp_kata.write('\n')
    cmp_kata.write(b + e + j)
    cmp_kata.write('\n')
    cmp_kata.write(b + f + a)
    cmp_kata.write('\n')
    cmp_kata.write(b + f + b)
    cmp_kata.write('\n')
    cmp_kata.write(b + f + c)
    cmp_kata.write('\n')
    cmp_kata.write(b + f + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + f + e)
    cmp_kata.write('\n')
    cmp_kata.write(b + f + f)
    cmp_kata.write('\n')
    cmp_kata.write(b + f + g)
    cmp_kata.write('\n')
    cmp_kata.write(b + f + h)
    cmp_kata.write('\n')
    cmp_kata.write(b + f + i)
    cmp_kata.write('\n')
    cmp_kata.write(b + f + j)
    cmp_kata.write('\n')
    cmp_kata.write(b + g + a)
    cmp_kata.write('\n')
    cmp_kata.write(b + g + b)
    cmp_kata.write('\n')
    cmp_kata.write(b + g + c)
    cmp_kata.write('\n')
    cmp_kata.write(b + g + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + g + e)
    cmp_kata.write('\n')
    cmp_kata.write(b + g + f)
    cmp_kata.write('\n')
    cmp_kata.write(b + g + g)
    cmp_kata.write('\n')
    cmp_kata.write(b + g + h)
    cmp_kata.write('\n')
    cmp_kata.write(b + g + i)
    cmp_kata.write('\n')
    cmp_kata.write(b + g + j)
    cmp_kata.write('\n')
    cmp_kata.write(b + h + a)
    cmp_kata.write('\n')
    cmp_kata.write(b + h + b)
    cmp_kata.write('\n')
    cmp_kata.write(a + b + c + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + h + c)
    cmp_kata.write('\n')
    cmp_kata.write(b + h + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + h + e)
    cmp_kata.write('\n')
    cmp_kata.write(b + h + f)
    cmp_kata.write('\n')
    cmp_kata.write(b + h + g)
    cmp_kata.write('\n')
    cmp_kata.write(b + h + h)
    cmp_kata.write('\n')
    cmp_kata.write(b + h + i)
    cmp_kata.write('\n')
    cmp_kata.write(b + h + j)
    cmp_kata.write('\n')
    cmp_kata.write(b + i + a)
    cmp_kata.write('\n')
    cmp_kata.write(b + i + b)
    cmp_kata.write('\n')
    cmp_kata.write(b + i + c)
    cmp_kata.write('\n')
    cmp_kata.write(b + i + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + i + e)
    cmp_kata.write('\n')
    cmp_kata.write(b + i + f)
    cmp_kata.write('\n')
    cmp_kata.write(b + i + g)
    cmp_kata.write('\n')
    cmp_kata.write(b + i + h)
    cmp_kata.write('\n')
    cmp_kata.write(b + i + i)
    cmp_kata.write('\n')
    cmp_kata.write(b + i + j)
    cmp_kata.write('\n')
    cmp_kata.write(b + j + a)
    cmp_kata.write('\n')
    cmp_kata.write(b + j + b)
    cmp_kata.write('\n')
    cmp_kata.write(b + j + c)
    cmp_kata.write('\n')
    cmp_kata.write(b + j + d)
    cmp_kata.write('\n')
    cmp_kata.write(b + j + e)
    cmp_kata.write('\n')
    cmp_kata.write(b + j + f)
    cmp_kata.write('\n')
    cmp_kata.write(b + j + g)
    cmp_kata.write('\n')
    cmp_kata.write(b + j + h)
    cmp_kata.write('\n')
    cmp_kata.write(b + j + i)
    cmp_kata.write('\n')
    cmp_kata.write(b + j + j)
    cmp_kata.write('\n')
    cmp_kata.write(c + a + b)
    cmp_kata.write('\n')
    cmp_kata.write(c + a + c)
    cmp_kata.write('\n')
    cmp_kata.write(c + a + d)
    cmp_kata.write('\n')
    cmp_kata.write(c + a + e)
    cmp_kata.write('\n')
    cmp_kata.write(c + a + f)
    cmp_kata.write('\n')
    cmp_kata.write(c + a + g)
    cmp_kata.write('\n')
    cmp_kata.write(c + a + h)
    cmp_kata.write('\n')
    cmp_kata.write(c + a + i)
    cmp_kata.write('\n')
    cmp_kata.write(c + a + j)
    cmp_kata.write('\n')
    cmp_kata.write(c + b + a)
    cmp_kata.write('\n')
    cmp_kata.write(c + b + b)
    cmp_kata.write('\n')
    cmp_kata.write(c + b + c)
    cmp_kata.write('\n')
    cmp_kata.write(c + b + d)
    cmp_kata.write('\n')
    cmp_kata.write(c + b + e)
    cmp_kata.write('\n')
    cmp_kata.write(c + b + f)
    cmp_kata.write('\n')
    cmp_kata.write(c + b + g)
    cmp_kata.write('\n')
    cmp_kata.write(c + b + h)
    cmp_kata.write('\n')
    cmp_kata.write(c + b + i)
    cmp_kata.write('\n')
    cmp_kata.write(c + b + j)
    cmp_kata.write('\n')
    cmp_kata.write(c + c + a)
    cmp_kata.write('\n')
    cmp_kata.write(c + c + b)
    cmp_kata.write('\n')
    cmp_kata.write(c + c + c)
    cmp_kata.write('\n')
    cmp_kata.write(c + c + d)
    cmp_kata.write('\n')
    cmp_kata.write(c + c + e)
    cmp_kata.write('\n')
    cmp_kata.write(c + c + f)
    cmp_kata.write('\n')
    cmp_kata.write(c + c + g)
    cmp_kata.write('\n')
    cmp_kata.write(c + c + h)
    cmp_kata.write('\n')
    cmp_kata.write(c + c + i)
    cmp_kata.write('\n')
    cmp_kata.write(c + c + j)
    cmp_kata.write('\n')
    cmp_kata.write(c + d + a)
    cmp_kata.write('\n')
    cmp_kata.write(c + d + b)
    cmp_kata.write('\n')
    cmp_kata.write(c + d + c)
    cmp_kata.write('\n')
    cmp_kata.write(c + d + d)
    cmp_kata.write('\n')
    cmp_kata.write(c + d + e)
    cmp_kata.write('\n')
    cmp_kata.write(c + d + f)
    cmp_kata.write('\n')
    cmp_kata.write(c + d + g)
    cmp_kata.write('\n')
    cmp_kata.write(c + d + h)
    cmp_kata.write('\n')
    cmp_kata.write(c + d + i)
    cmp_kata.write('\n')
    cmp_kata.write(c + d + j)
    cmp_kata.write('\n')
    cmp_kata.write(c + e + a)
    cmp_kata.write('\n')
    cmp_kata.write(c + e + b)
    cmp_kata.write('\n')
    cmp_kata.write(c + e + c)
    cmp_kata.write('\n')
    cmp_kata.write(c + e + d)
    cmp_kata.write('\n')
    cmp_kata.write(c + e + e)
    cmp_kata.write('\n')
    cmp_kata.write(c + e + f)
    cmp_kata.write('\n')
    cmp_kata.write(c + e + g)
    cmp_kata.write('\n')
    cmp_kata.write(c + e + h)
    cmp_kata.write('\n')
    cmp_kata.write(c + e + i)
    cmp_kata.write('\n')
    cmp_kata.write(c + e + j)
    cmp_kata.write('\n')
    cmp_kata.write(c + f + a)
    cmp_kata.write('\n')
    cmp_kata.write(c + f + b)
    cmp_kata.write('\n')
    cmp_kata.write(c + f + c)
    cmp_kata.write('\n')
    cmp_kata.write(c + f + d)
    cmp_kata.write('\n')
    cmp_kata.write(c + f + e)
    cmp_kata.write('\n')
    cmp_kata.write(c + f + f)
    cmp_kata.write('\n')
    cmp_kata.write(c + f + g)
    cmp_kata.write('\n')
    cmp_kata.write(c + f + h)
    cmp_kata.write('\n')
    cmp_kata.write(c + f + i)
    cmp_kata.write('\n')
    cmp_kata.write(c + f + j)
    cmp_kata.write('\n')
    cmp_kata.write(c + g + a)
    cmp_kata.write('\n')
    cmp_kata.write(c + g + b)
    cmp_kata.write('\n')
    cmp_kata.write(c + g + c)
    cmp_kata.write('\n')
    cmp_kata.write(c + g + d)
    cmp_kata.write('\n')
    cmp_kata.write(c + g + e)
    cmp_kata.write('\n')
    cmp_kata.write(c + g + f)
    cmp_kata.write('\n')
    cmp_kata.write(c + g + g)
    cmp_kata.write('\n')
    cmp_kata.write(c + g + h)
    cmp_kata.write('\n')
    cmp_kata.write(c + g + i)
    cmp_kata.write('\n')
    cmp_kata.write(c + g + j)
    cmp_kata.write('\n')
    cmp_kata.write(c + h + a)
    cmp_kata.write('\n')
    cmp_kata.write(c + h + b)
    cmp_kata.write('\n')
    cmp_kata.write(c + h + c)
    cmp_kata.write('\n')
    cmp_kata.write(c + h + d)
    cmp_kata.write('\n')
    cmp_kata.write(c + h + e)
    cmp_kata.write('\n')
    cmp_kata.write(c + h + f)
    cmp_kata.write('\n')
    cmp_kata.write(c + h + g)
    cmp_kata.write('\n')
    cmp_kata.write(c + h + h)
    cmp_kata.write('\n')
    cmp_kata.write(c + h + i)
    cmp_kata.write('\n')
    cmp_kata.write(c + h + j)
    cmp_kata.write('\n')
    cmp_kata.write(c + i + a)
    cmp_kata.write('\n')
    cmp_kata.write(c + i + b)
    cmp_kata.write('\n')
    cmp_kata.write(c + i + c)
    cmp_kata.write('\n')
    cmp_kata.write(c + i + d)
    cmp_kata.write('\n')
    cmp_kata.write(c + i + e)
    cmp_kata.write('\n')
    cmp_kata.write(c + i + f)
    cmp_kata.write('\n')
    cmp_kata.write(c + i + g)
    cmp_kata.write('\n')
    cmp_kata.write(c + i + h)
    cmp_kata.write('\n')
    cmp_kata.write(c + i + i)
    cmp_kata.write('\n')
    cmp_kata.write(c + i + j)
    cmp_kata.write('\n')
    cmp_kata.write(c + j + a)
    cmp_kata.write('\n')
    cmp_kata.write(c + j + b)
    cmp_kata.write('\n')
    cmp_kata.write(c + j + c)
    cmp_kata.write('\n')
    cmp_kata.write(c + j + d)
    cmp_kata.write('\n')
    cmp_kata.write(c + j + e)
    cmp_kata.write('\n')
    cmp_kata.write(c + j + f)
    cmp_kata.write('\n')
    cmp_kata.write(c + j + g)
    cmp_kata.write('\n')
    cmp_kata.write(c + j + h)
    cmp_kata.write('\n')
    cmp_kata.write(c + j + i)
    cmp_kata.write('\n')
    cmp_kata.write(c + j + j)
    cmp_kata.write('\n')
    cmp_kata.write(d + a + b)
    cmp_kata.write('\n')
    cmp_kata.write(d + a + c)
    cmp_kata.write('\n')
    cmp_kata.write(d + a + d)
    cmp_kata.write('\n')
    cmp_kata.write(d + a + e)
    cmp_kata.write('\n')
    cmp_kata.write(d + a + f)
    cmp_kata.write('\n')
    cmp_kata.write(d + a + g)
    cmp_kata.write('\n')
    cmp_kata.write(d + a + h)
    cmp_kata.write('\n')
    cmp_kata.write(d + a + i)
    cmp_kata.write('\n')
    cmp_kata.write(d + a + j)
    cmp_kata.write('\n')
    cmp_kata.write(d + b + a)
    cmp_kata.write('\n')
    cmp_kata.write(d + b + b)
    cmp_kata.write('\n')
    cmp_kata.write(d + b + c)
    cmp_kata.write('\n')
    cmp_kata.write(d + b + d)
    cmp_kata.write('\n')
    cmp_kata.write(d + b + e)
    cmp_kata.write('\n')
    cmp_kata.write(d + b + f)
    cmp_kata.write('\n')
    cmp_kata.write(d + b + g)
    cmp_kata.write('\n')
    cmp_kata.write(d + b + h)
    cmp_kata.write('\n')
    cmp_kata.write(d + b + i)
    cmp_kata.write('\n')
    cmp_kata.write(d + b + j)
    cmp_kata.write('\n')
    cmp_kata.write(d + c + a)
    cmp_kata.write('\n')
    cmp_kata.write(d + c + b)
    cmp_kata.write('\n')
    cmp_kata.write(d + c + c)
    cmp_kata.write('\n')
    cmp_kata.write(d + c + d)
    cmp_kata.write('\n')
    cmp_kata.write(d + c + e)
    cmp_kata.write('\n')
    cmp_kata.write(d + c + f)
    cmp_kata.write('\n')
    cmp_kata.write(d + c + g)
    cmp_kata.write('\n')
    cmp_kata.write(d + c + h)
    cmp_kata.write('\n')
    cmp_kata.write(d + c + i)
    cmp_kata.write('\n')
    cmp_kata.write(d + c + j)
    cmp_kata.write('\n')
    cmp_kata.write(d + d + a)
    cmp_kata.write('\n')
    cmp_kata.write(d + d + b)
    cmp_kata.write('\n')
    cmp_kata.write(d + d + c)
    cmp_kata.write('\n')
    cmp_kata.write(d + d + d)
    cmp_kata.write('\n')
    cmp_kata.write(d + d + e)
    cmp_kata.write('\n')
    cmp_kata.write(d + d + f)
    cmp_kata.write('\n')
    cmp_kata.write(d + d + g)
    cmp_kata.write('\n')
    cmp_kata.write(d + d + h)
    cmp_kata.write('\n')
    cmp_kata.write(d + d + i)
    cmp_kata.write('\n')
    cmp_kata.write(d + d + j)
    cmp_kata.write('\n')
    cmp_kata.write(d + e + a)
    cmp_kata.write('\n')
    cmp_kata.write(d + e + b)
    cmp_kata.write('\n')
    cmp_kata.write(d + e + c)
    cmp_kata.write('\n')
    cmp_kata.write(d + e + d)
    cmp_kata.write('\n')
    cmp_kata.write(d + e + e)
    cmp_kata.write('\n')
    cmp_kata.write(d + e + f)
    cmp_kata.write('\n')
    cmp_kata.write(d + e + g)
    cmp_kata.write('\n')
    cmp_kata.write(d + e + h)
    cmp_kata.write('\n')
    cmp_kata.write(d + e + i)
    cmp_kata.write('\n')
    cmp_kata.write(d + e + j)
    cmp_kata.write('\n')
    cmp_kata.write(d + f + a)
    cmp_kata.write('\n')
    cmp_kata.write(d + f + b)
    cmp_kata.write('\n')
    cmp_kata.write(d + f + c)
    cmp_kata.write('\n')
    cmp_kata.write(d + f + d)
    cmp_kata.write('\n')
    cmp_kata.write(d + f + e)
    cmp_kata.write('\n')
    cmp_kata.write(d + f + f)
    cmp_kata.write('\n')
    cmp_kata.write(d + f + g)
    cmp_kata.write('\n')
    cmp_kata.write(d + f + h)
    cmp_kata.write('\n')
    cmp_kata.write(d + f + i)
    cmp_kata.write('\n')
    cmp_kata.write(d + f + j)
    cmp_kata.write('\n')
    cmp_kata.write(d + g + a)
    cmp_kata.write('\n')
    cmp_kata.write(d + g + b)
    cmp_kata.write('\n')
    cmp_kata.write(d + g + c)
    cmp_kata.write('\n')
    cmp_kata.write(d + g + d)
    cmp_kata.write('\n')
    cmp_kata.write(d + g + e)
    cmp_kata.write('\n')
    cmp_kata.write(d + g + f)
    cmp_kata.write('\n')
    cmp_kata.write(d + g + g)
    cmp_kata.write('\n')
    cmp_kata.write(d + g + h)
    cmp_kata.write('\n')
    cmp_kata.write(d + g + i)
    cmp_kata.write('\n')
    cmp_kata.write(d + g + j)
    cmp_kata.write('\n')
    cmp_kata.write(d + h + a)
    cmp_kata.write('\n')
    cmp_kata.write(d + h + b)
    cmp_kata.write('\n')
    cmp_kata.write(d + h + c)
    cmp_kata.write('\n')
    cmp_kata.write(d + h + d)
    cmp_kata.write('\n')
    cmp_kata.write(d + h + e)
    cmp_kata.write('\n')
    cmp_kata.write(d + h + f)
    cmp_kata.write('\n')
    cmp_kata.write(d + h + g)
    cmp_kata.write('\n')
    cmp_kata.write(d + h + h)
    cmp_kata.write('\n')
    cmp_kata.write(d + h + i)
    cmp_kata.write('\n')
    cmp_kata.write(d + h + j)
    cmp_kata.write('\n')
    cmp_kata.write(d + i + a)
    cmp_kata.write('\n')
    cmp_kata.write(d + i + b)
    cmp_kata.write('\n')
    cmp_kata.write(d + i + c)
    cmp_kata.write('\n')
    cmp_kata.write(d + i + d)
    cmp_kata.write('\n')
    cmp_kata.write(d + i + e)
    cmp_kata.write('\n')
    cmp_kata.write(d + i + f)
    cmp_kata.write('\n')
    cmp_kata.write(d + i + g)
    cmp_kata.write('\n')
    cmp_kata.write(d + i + h)
    cmp_kata.write('\n')
    cmp_kata.write(d + i + i)
    cmp_kata.write('\n')
    cmp_kata.write(d + i + j)
    cmp_kata.write('\n')
    cmp_kata.write(d + j + a)
    cmp_kata.write('\n')
    cmp_kata.write(d + j + b)
    cmp_kata.write('\n')
    cmp_kata.write(d + j + c)
    cmp_kata.write('\n')
    cmp_kata.write(d + j + d)
    cmp_kata.write('\n')
    cmp_kata.write(d + j + e)
    cmp_kata.write('\n')
    cmp_kata.write(d + j + f)
    cmp_kata.write('\n')
    cmp_kata.write(d + j + g)
    cmp_kata.write('\n')
    cmp_kata.write(d + j + h)
    cmp_kata.write('\n')
    cmp_kata.write(d + j + i)
    cmp_kata.write('\n')
    cmp_kata.write(d + j + j)
    cmp_kata.write('\n')
    cmp_kata.write(e + a + b)
    cmp_kata.write('\n')
    cmp_kata.write(e + a + c)
    cmp_kata.write('\n')
    cmp_kata.write(e + a + d)
    cmp_kata.write('\n')
    cmp_kata.write(e + a + e)
    cmp_kata.write('\n')
    cmp_kata.write(e + a + f)
    cmp_kata.write('\n')
    cmp_kata.write(e + a + g)
    cmp_kata.write('\n')
    cmp_kata.write(e + a + h)
    cmp_kata.write('\n')
    cmp_kata.write(e + a + i)
    cmp_kata.write('\n')
    cmp_kata.write(e + a + j)
    cmp_kata.write('\n')
    cmp_kata.write(e + b + a)
    cmp_kata.write('\n')
    cmp_kata.write(e + b + b)
    cmp_kata.write('\n')
    cmp_kata.write(e + b + c)
    cmp_kata.write('\n')
    cmp_kata.write(e + b + d)
    cmp_kata.write('\n')
    cmp_kata.write(e + b + e)
    cmp_kata.write('\n')
    cmp_kata.write(e + b + f)
    cmp_kata.write('\n')
    cmp_kata.write(e + b + g)
    cmp_kata.write('\n')
    cmp_kata.write(e + b + h)
    cmp_kata.write('\n')
    cmp_kata.write(e + b + i)
    cmp_kata.write('\n')
    cmp_kata.write(e + b + j)
    cmp_kata.write('\n')
    cmp_kata.write(e + c + a)
    cmp_kata.write('\n')
    cmp_kata.write(e + c + b)
    cmp_kata.write('\n')
    cmp_kata.write(e + c + c)
    cmp_kata.write('\n')
    cmp_kata.write(e + c + d)
    cmp_kata.write('\n')
    cmp_kata.write(e + c + e)
    cmp_kata.write('\n')
    cmp_kata.write(e + c + f)
    cmp_kata.write('\n')
    cmp_kata.write(e + c + g)
    cmp_kata.write('\n')
    cmp_kata.write(e + c + h)
    cmp_kata.write('\n')
    cmp_kata.write(e + c + i)
    cmp_kata.write('\n')
    cmp_kata.write(e + c + j)
    cmp_kata.write('\n')
    cmp_kata.write(e + d + a)
    cmp_kata.write('\n')
    cmp_kata.write(e + d + b)
    cmp_kata.write('\n')
    cmp_kata.write(e + d + c)
    cmp_kata.write('\n')
    cmp_kata.write(e + d + d)
    cmp_kata.write('\n')
    cmp_kata.write(e + d + e)
    cmp_kata.write('\n')
    cmp_kata.write(e + d + f)
    cmp_kata.write('\n')
    cmp_kata.write(e + d + g)
    cmp_kata.write('\n')
    cmp_kata.write(e + d + h)
    cmp_kata.write('\n')
    cmp_kata.write(e + d + i)
    cmp_kata.write('\n')
    cmp_kata.write(e + d + j)
    cmp_kata.write('\n')
    cmp_kata.write(e + e + a)
    cmp_kata.write('\n')
    cmp_kata.write(e + e + b)
    cmp_kata.write('\n')
    cmp_kata.write(e + e + c)
    cmp_kata.write('\n')
    cmp_kata.write(e + e + d)
    cmp_kata.write('\n')
    cmp_kata.write(e + e + e)
    cmp_kata.write('\n')
    cmp_kata.write(e + e + f)
    cmp_kata.write('\n')
    cmp_kata.write(e + e + g)
    cmp_kata.write('\n')
    cmp_kata.write(e + e + h)
    cmp_kata.write('\n')
    cmp_kata.write(e + e + i)
    cmp_kata.write('\n')
    cmp_kata.write(e + e + j)
    cmp_kata.write('\n')
    cmp_kata.write(e + f + a)
    cmp_kata.write('\n')
    cmp_kata.write(e + f + b)
    cmp_kata.write('\n')
    cmp_kata.write(e + f + c)
    cmp_kata.write('\n')
    cmp_kata.write(e + f + d)
    cmp_kata.write('\n')
    cmp_kata.write(e + f + e)
    cmp_kata.write('\n')
    cmp_kata.write(e + f + f)
    cmp_kata.write('\n')
    cmp_kata.write(e + f + g)
    cmp_kata.write('\n')
    cmp_kata.write(e + f + h)
    cmp_kata.write('\n')
    cmp_kata.write(e + f + i)
    cmp_kata.write('\n')
    cmp_kata.write(e + f + j)
    cmp_kata.write('\n')
    cmp_kata.write(e + g + a)
    cmp_kata.write('\n')
    cmp_kata.write(e + g + b)
    cmp_kata.write('\n')
    cmp_kata.write(e + g + c)
    cmp_kata.write('\n')
    cmp_kata.write(e + g + d)
    cmp_kata.write('\n')
    cmp_kata.write(e + g + e)
    cmp_kata.write('\n')
    cmp_kata.write(e + g + f)
    cmp_kata.write('\n')
    cmp_kata.write(e + g + g)
    cmp_kata.write('\n')
    cmp_kata.write(e + g + h)
    cmp_kata.write('\n')
    cmp_kata.write(e + g + i)
    cmp_kata.write('\n')
    cmp_kata.write(e + g + j)
    cmp_kata.write('\n')
    cmp_kata.write(e + h + a)
    cmp_kata.write('\n')
    cmp_kata.write(e + h + b)
    cmp_kata.write('\n')
    cmp_kata.write(e + h + c)
    cmp_kata.write('\n')
    cmp_kata.write(e + h + d)
    cmp_kata.write('\n')
    cmp_kata.write(e + h + e)
    cmp_kata.write('\n')
    cmp_kata.write(e + h + f)
    cmp_kata.write('\n')
    cmp_kata.write(e + h + g)
    cmp_kata.write('\n')
    cmp_kata.write(e + h + h)
    cmp_kata.write('\n')
    cmp_kata.write(e + h + i)
    cmp_kata.write('\n')
    cmp_kata.write(e + h + j)
    cmp_kata.write('\n')
    cmp_kata.write(e + i + a)
    cmp_kata.write('\n')
    cmp_kata.write(e + i + b)
    cmp_kata.write('\n')
    cmp_kata.write(e + i + c)
    cmp_kata.write('\n')
    cmp_kata.write(e + i + d)
    cmp_kata.write('\n')
    cmp_kata.write(e + i + e)
    cmp_kata.write('\n')
    cmp_kata.write(e + i + f)
    cmp_kata.write('\n')
    cmp_kata.write(e + i + g)
    cmp_kata.write('\n')
    cmp_kata.write(e + i + h)
    cmp_kata.write('\n')
    cmp_kata.write(e + i + i)
    cmp_kata.write('\n')
    cmp_kata.write(e + i + j)
    cmp_kata.write('\n')
    cmp_kata.write(e + j + a)
    cmp_kata.write('\n')
    cmp_kata.write(e + j + b)
    cmp_kata.write('\n')
    cmp_kata.write(e + j + c)
    cmp_kata.write('\n')
    cmp_kata.write(e + j + d)
    cmp_kata.write('\n')
    cmp_kata.write(e + j + e)
    cmp_kata.write('\n')
    cmp_kata.write(e + j + f)
    cmp_kata.write('\n')
    cmp_kata.write(e + j + g)
    cmp_kata.write('\n')
    cmp_kata.write(e + j + h)
    cmp_kata.write('\n')
    cmp_kata.write(e + j + i)
    cmp_kata.write('\n')
    cmp_kata.write(e + j + j)
    cmp_kata.write('\n')
    cmp_kata.write(f + a + b)
    cmp_kata.write('\n')
    cmp_kata.write(f + a + c)
    cmp_kata.write('\n')
    cmp_kata.write(f + a + d)
    cmp_kata.write('\n')
    cmp_kata.write(f + a + e)
    cmp_kata.write('\n')
    cmp_kata.write(f + a + f)
    cmp_kata.write('\n')
    cmp_kata.write(f + a + g)
    cmp_kata.write('\n')
    cmp_kata.write(f + a + h)
    cmp_kata.write('\n')
    cmp_kata.write(f + a + i)
    cmp_kata.write('\n')
    cmp_kata.write(f + a + j)
    cmp_kata.write('\n')
    cmp_kata.write(f + b + a)
    cmp_kata.write('\n')
    cmp_kata.write(f + b + b)
    cmp_kata.write('\n')
    cmp_kata.write(f + b + c)
    cmp_kata.write('\n')
    cmp_kata.write(f + b + d)
    cmp_kata.write('\n')
    cmp_kata.write(f + b + e)
    cmp_kata.write('\n')
    cmp_kata.write(f + b + f)
    cmp_kata.write('\n')
    cmp_kata.write(f + b + g)
    cmp_kata.write('\n')
    cmp_kata.write(f + b + h)
    cmp_kata.write('\n')
    cmp_kata.write(f + b + i)
    cmp_kata.write('\n')
    cmp_kata.write(f + b + j)
    cmp_kata.write('\n')
    cmp_kata.write(f + c + a)
    cmp_kata.write('\n')
    cmp_kata.write(f + c + b)
    cmp_kata.write('\n')
    cmp_kata.write(f + c + c)
    cmp_kata.write('\n')
    cmp_kata.write(f + c + d)
    cmp_kata.write('\n')
    cmp_kata.write(f + c + e)
    cmp_kata.write('\n')
    cmp_kata.write(f + c + f)
    cmp_kata.write('\n')
    cmp_kata.write(f + c + g)
    cmp_kata.write('\n')
    cmp_kata.write(f + c + h)
    cmp_kata.write('\n')
    cmp_kata.write(f + c + i)
    cmp_kata.write('\n')
    cmp_kata.write(f + c + j)
    cmp_kata.write('\n')
    cmp_kata.write(f + d + a)
    cmp_kata.write('\n')
    cmp_kata.write(f + d + b)
    cmp_kata.write('\n')
    cmp_kata.write(f + d + c)
    cmp_kata.write('\n')
    cmp_kata.write(f + d + d)
    cmp_kata.write('\n')
    cmp_kata.write(f + d + e)
    cmp_kata.write('\n')
    cmp_kata.write(f + d + f)
    cmp_kata.write('\n')
    cmp_kata.write(f + d + g)
    cmp_kata.write('\n')
    cmp_kata.write(f + d + h)
    cmp_kata.write('\n')
    cmp_kata.write(f + d + i)
    cmp_kata.write('\n')
    cmp_kata.write(f + d + j)
    cmp_kata.write('\n')
    cmp_kata.write(f + e + a)
    cmp_kata.write('\n')
    cmp_kata.write(f + e + b)
    cmp_kata.write('\n')
    cmp_kata.write(f + e + c)
    cmp_kata.write('\n')
    cmp_kata.write(f + e + d)
    cmp_kata.write('\n')
    cmp_kata.write(f + e + e)
    cmp_kata.write('\n')
    cmp_kata.write(f + e + f)
    cmp_kata.write('\n')
    cmp_kata.write(f + e + g)
    cmp_kata.write('\n')
    cmp_kata.write(f + e + h)
    cmp_kata.write('\n')
    cmp_kata.write(f + e + i)
    cmp_kata.write('\n')
    cmp_kata.write(f + e + j)
    cmp_kata.write('\n')
    cmp_kata.write(f + f + a)
    cmp_kata.write('\n')
    cmp_kata.write(f + f + b)
    cmp_kata.write('\n')
    cmp_kata.write(f + f + c)
    cmp_kata.write('\n')
    cmp_kata.write(f + f + d)
    cmp_kata.write('\n')
    cmp_kata.write(f + f + e)
    cmp_kata.write('\n')
    cmp_kata.write(f + f + f)
    cmp_kata.write('\n')
    cmp_kata.write(f + f + g)
    cmp_kata.write('\n')
    cmp_kata.write(f + f + h)
    cmp_kata.write('\n')
    cmp_kata.write(f + f + i)
    cmp_kata.write('\n')
    cmp_kata.write(f + f + j)
    cmp_kata.write('\n')
    cmp_kata.write(f + g + a)
    cmp_kata.write('\n')
    cmp_kata.write(f + g + b)
    cmp_kata.write('\n')
    cmp_kata.write(f + g + c)
    cmp_kata.write('\n')
    cmp_kata.write(f + g + d)
    cmp_kata.write('\n')
    cmp_kata.write(f + g + e)
    cmp_kata.write('\n')
    cmp_kata.write(f + g + f)
    cmp_kata.write('\n')
    cmp_kata.write(f + g + g)
    cmp_kata.write('\n')
    cmp_kata.write(f + g + h)
    cmp_kata.write('\n')
    cmp_kata.write(f + g + i)
    cmp_kata.write('\n')
    cmp_kata.write(f + g + j)
    cmp_kata.write('\n')
    cmp_kata.write(f + h + a)
    cmp_kata.write('\n')
    cmp_kata.write(f + h + b)
    cmp_kata.write('\n')
    cmp_kata.write(f + h + c)
    cmp_kata.write('\n')
    cmp_kata.write(f + h + d)
    cmp_kata.write('\n')
    cmp_kata.write(f + h + e)
    cmp_kata.write('\n')
    cmp_kata.write(f + h + f)
    cmp_kata.write('\n')
    cmp_kata.write(f + h + g)
    cmp_kata.write('\n')
    cmp_kata.write(f + h + h)
    cmp_kata.write('\n')
    cmp_kata.write(f + h + i)
    cmp_kata.write('\n')
    cmp_kata.write(f + h + j)
    cmp_kata.write('\n')
    cmp_kata.write(f + i + a)
    cmp_kata.write('\n')
    cmp_kata.write(f + i + b)
    cmp_kata.write('\n')
    cmp_kata.write(f + i + c)
    cmp_kata.write('\n')
    cmp_kata.write(f + i + d)
    cmp_kata.write('\n')
    cmp_kata.write(f + i + e)
    cmp_kata.write('\n')
    cmp_kata.write(f + i + f)
    cmp_kata.write('\n')
    cmp_kata.write(f + i + g)
    cmp_kata.write('\n')
    cmp_kata.write(f + i + h)
    cmp_kata.write('\n')
    cmp_kata.write(f + i + i)
    cmp_kata.write('\n')
    cmp_kata.write(f + i + j)
    cmp_kata.write('\n')
    cmp_kata.write(f + j + a)
    cmp_kata.write('\n')
    cmp_kata.write(f + j + b)
    cmp_kata.write('\n')
    cmp_kata.write(f + j + c)
    cmp_kata.write('\n')
    cmp_kata.write(f + j + d)
    cmp_kata.write('\n')
    cmp_kata.write(f + j + e)
    cmp_kata.write('\n')
    cmp_kata.write(f + j + f)
    cmp_kata.write('\n')
    cmp_kata.write(f + j + g)
    cmp_kata.write('\n')
    cmp_kata.write(f + j + h)
    cmp_kata.write('\n')
    cmp_kata.write(f + j + i)
    cmp_kata.write('\n')
    cmp_kata.write(f + j + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + a + b)
    cmp_kata.write('\n')
    cmp_kata.write(g + a + c)
    cmp_kata.write('\n')
    cmp_kata.write(g + a + d)
    cmp_kata.write('\n')
    cmp_kata.write(g + a + e)
    cmp_kata.write('\n')
    cmp_kata.write(g + a + f)
    cmp_kata.write('\n')
    cmp_kata.write(g + a + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + a + h)
    cmp_kata.write('\n')
    cmp_kata.write(g + a + i)
    cmp_kata.write('\n')
    cmp_kata.write(g + a + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + a)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + b)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + c)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + d)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + e)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + f)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + h)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + i)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + a)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + b)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + c)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + d)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + e)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + f)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + h + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + i + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(g + b + j + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + a + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + b + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + c + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + d + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + e + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + f + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + g + birthday)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + h)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + i)
    cmp_kata.write('\n')
    cmp_kata.write(g + c + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + d + a)
    cmp_kata.write('\n')
    cmp_kata.write(g + d + b)
    cmp_kata.write('\n')
    cmp_kata.write(g + d + c)
    cmp_kata.write('\n')
    cmp_kata.write(g + d + d)
    cmp_kata.write('\n')
    cmp_kata.write(g + d + e)
    cmp_kata.write('\n')
    cmp_kata.write(g + d + f)
    cmp_kata.write('\n')
    cmp_kata.write(g + d + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + d + h)
    cmp_kata.write('\n')
    cmp_kata.write(g + d + i)
    cmp_kata.write('\n')
    cmp_kata.write(g + d + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + e + a)
    cmp_kata.write('\n')
    cmp_kata.write(g + e + b)
    cmp_kata.write('\n')
    cmp_kata.write(g + e + c)
    cmp_kata.write('\n')
    cmp_kata.write(g + e + d)
    cmp_kata.write('\n')
    cmp_kata.write(g + e + e)
    cmp_kata.write('\n')
    cmp_kata.write(g + e + f)
    cmp_kata.write('\n')
    cmp_kata.write(g + e + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + e + h)
    cmp_kata.write('\n')
    cmp_kata.write(g + e + i)
    cmp_kata.write('\n')
    cmp_kata.write(g + e + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + f + a)
    cmp_kata.write('\n')
    cmp_kata.write(g + f + b)
    cmp_kata.write('\n')
    cmp_kata.write(g + f + c)
    cmp_kata.write('\n')
    cmp_kata.write(g + f + d)
    cmp_kata.write('\n')
    cmp_kata.write(g + f + e)
    cmp_kata.write('\n')
    cmp_kata.write(g + f + f)
    cmp_kata.write('\n')
    cmp_kata.write(g + f + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + f + h)
    cmp_kata.write('\n')
    cmp_kata.write(g + f + i)
    cmp_kata.write('\n')
    cmp_kata.write(g + f + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + g + a)
    cmp_kata.write('\n')
    cmp_kata.write(g + g + b)
    cmp_kata.write('\n')
    cmp_kata.write(g + g + c)
    cmp_kata.write('\n')
    cmp_kata.write(g + g + d)
    cmp_kata.write('\n')
    cmp_kata.write(g + g + e)
    cmp_kata.write('\n')
    cmp_kata.write(g + g + f)
    cmp_kata.write('\n')
    cmp_kata.write(g + g + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + g + h)
    cmp_kata.write('\n')
    cmp_kata.write(g + g + i)
    cmp_kata.write('\n')
    cmp_kata.write(g + g + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + h + a)
    cmp_kata.write('\n')
    cmp_kata.write(g + h + b)
    cmp_kata.write('\n')
    cmp_kata.write(g + h + c)
    cmp_kata.write('\n')
    cmp_kata.write(g + h + d)
    cmp_kata.write('\n')
    cmp_kata.write(g + h + e)
    cmp_kata.write('\n')
    cmp_kata.write(g + h + f)
    cmp_kata.write('\n')
    cmp_kata.write(g + h + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + h + h)
    cmp_kata.write('\n')
    cmp_kata.write(g + h + i)
    cmp_kata.write('\n')
    cmp_kata.write(g + h + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + i + a)
    cmp_kata.write('\n')
    cmp_kata.write(g + i + b)
    cmp_kata.write('\n')
    cmp_kata.write(g + i + c)
    cmp_kata.write('\n')
    cmp_kata.write(g + i + d)
    cmp_kata.write('\n')
    cmp_kata.write(g + i + e)
    cmp_kata.write('\n')
    cmp_kata.write(g + i + f)
    cmp_kata.write('\n')
    cmp_kata.write(g + i + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + i + h)
    cmp_kata.write('\n')
    cmp_kata.write(g + i + i)
    cmp_kata.write('\n')
    cmp_kata.write(g + i + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + j + a)
    cmp_kata.write('\n')
    cmp_kata.write(g + j + b)
    cmp_kata.write('\n')
    cmp_kata.write(g + j + c)
    cmp_kata.write('\n')
    cmp_kata.write(g + j + d)
    cmp_kata.write('\n')
    cmp_kata.write(g + j + e)
    cmp_kata.write('\n')
    cmp_kata.write(g + j + f)
    cmp_kata.write('\n')
    cmp_kata.write(g + j + g)
    cmp_kata.write('\n')
    cmp_kata.write(g + j + h)
    cmp_kata.write('\n')
    cmp_kata.write(g + j + i)
    cmp_kata.write('\n')
    cmp_kata.write(g + j + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + a + b)
    cmp_kata.write('\n')
    cmp_kata.write(h + a + c)
    cmp_kata.write('\n')
    cmp_kata.write(h + a + d)
    cmp_kata.write('\n')
    cmp_kata.write(h + a + e)
    cmp_kata.write('\n')
    cmp_kata.write(h + a + f)
    cmp_kata.write('\n')
    cmp_kata.write(h + a + g)
    cmp_kata.write('\n')
    cmp_kata.write(h + a + h)
    cmp_kata.write('\n')
    cmp_kata.write(h + a + i)
    cmp_kata.write('\n')
    cmp_kata.write(h + a + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + b + a)
    cmp_kata.write('\n')
    cmp_kata.write(h + b + b)
    cmp_kata.write('\n')
    cmp_kata.write(h + b + c)
    cmp_kata.write('\n')
    cmp_kata.write(h + b + d)
    cmp_kata.write('\n')
    cmp_kata.write(h + b + e)
    cmp_kata.write('\n')
    cmp_kata.write(h + b + f)
    cmp_kata.write('\n')
    cmp_kata.write(h + b + g)
    cmp_kata.write('\n')
    cmp_kata.write(h + b + h)
    cmp_kata.write('\n')
    cmp_kata.write(h + b + i)
    cmp_kata.write('\n')
    cmp_kata.write(h + b + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + c + a)
    cmp_kata.write('\n')
    cmp_kata.write(h + c + b)
    cmp_kata.write('\n')
    cmp_kata.write(h + c + c)
    cmp_kata.write('\n')
    cmp_kata.write(h + c + d)
    cmp_kata.write('\n')
    cmp_kata.write(h + c + e)
    cmp_kata.write('\n')
    cmp_kata.write(h + c + f)
    cmp_kata.write('\n')
    cmp_kata.write(h + c + g)
    cmp_kata.write('\n')
    cmp_kata.write(h + c + h)
    cmp_kata.write('\n')
    cmp_kata.write(h + c + i)
    cmp_kata.write('\n')
    cmp_kata.write(h + c + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + d + a)
    cmp_kata.write('\n')
    cmp_kata.write(h + d + b)
    cmp_kata.write('\n')
    cmp_kata.write(h + d + c)
    cmp_kata.write('\n')
    cmp_kata.write(h + d + d)
    cmp_kata.write('\n')
    cmp_kata.write(h + d + e)
    cmp_kata.write('\n')
    cmp_kata.write(h + d + f)
    cmp_kata.write('\n')
    cmp_kata.write(h + d + g)
    cmp_kata.write('\n')
    cmp_kata.write(h + d + h)
    cmp_kata.write('\n')
    cmp_kata.write(h + d + i)
    cmp_kata.write('\n')
    cmp_kata.write(h + d + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + e + a)
    cmp_kata.write('\n')
    cmp_kata.write(h + e + b)
    cmp_kata.write('\n')
    cmp_kata.write(h + e + c)
    cmp_kata.write('\n')
    cmp_kata.write(h + e + d)
    cmp_kata.write('\n')
    cmp_kata.write(h + e + e)
    cmp_kata.write('\n')
    cmp_kata.write(h + e + f)
    cmp_kata.write('\n')
    cmp_kata.write(h + e + g)
    cmp_kata.write('\n')
    cmp_kata.write(h + e + h)
    cmp_kata.write('\n')
    cmp_kata.write(h + e + i)
    cmp_kata.write('\n')
    cmp_kata.write(h + e + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + f + a)
    cmp_kata.write('\n')
    cmp_kata.write(h + f + b)
    cmp_kata.write('\n')
    cmp_kata.write(h + f + c)
    cmp_kata.write('\n')
    cmp_kata.write(h + f + d)
    cmp_kata.write('\n')
    cmp_kata.write(h + f + e)
    cmp_kata.write('\n')
    cmp_kata.write(h + f + f)
    cmp_kata.write('\n')
    cmp_kata.write(h + f + g)
    cmp_kata.write('\n')
    cmp_kata.write(h + f + h)
    cmp_kata.write('\n')
    cmp_kata.write(h + f + i)
    cmp_kata.write('\n')
    cmp_kata.write(h + f + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + g + a)
    cmp_kata.write('\n')
    cmp_kata.write(h + g + b)
    cmp_kata.write('\n')
    cmp_kata.write(h + g + c)
    cmp_kata.write('\n')
    cmp_kata.write(h + g + d)
    cmp_kata.write('\n')
    cmp_kata.write(h + g + e)
    cmp_kata.write('\n')
    cmp_kata.write(h + g + f)
    cmp_kata.write('\n')
    cmp_kata.write(h + g + g)
    cmp_kata.write('\n')
    cmp_kata.write(h + g + h)
    cmp_kata.write('\n')
    cmp_kata.write(h + g + i)
    cmp_kata.write('\n')
    cmp_kata.write(h + g + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + h + a)
    cmp_kata.write('\n')
    cmp_kata.write(h + h + b)
    cmp_kata.write('\n')
    cmp_kata.write(h + h + c)
    cmp_kata.write('\n')
    cmp_kata.write(h + h + d)
    cmp_kata.write('\n')
    cmp_kata.write(h + h + e)
    cmp_kata.write('\n')
    cmp_kata.write(h + h + f)
    cmp_kata.write('\n')
    cmp_kata.write(h + h + g)
    cmp_kata.write('\n')
    cmp_kata.write(h + h + h)
    cmp_kata.write('\n')
    cmp_kata.write(h + h + i)
    cmp_kata.write('\n')
    cmp_kata.write(h + h + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + i + a)
    cmp_kata.write('\n')
    cmp_kata.write(h + i + b)
    cmp_kata.write('\n')
    cmp_kata.write(h + i + c)
    cmp_kata.write('\n')
    cmp_kata.write(h + i + d)
    cmp_kata.write('\n')
    cmp_kata.write(h + i + e)
    cmp_kata.write('\n')
    cmp_kata.write(h + i + f)
    cmp_kata.write('\n')
    cmp_kata.write(h + i + g)
    cmp_kata.write('\n')
    cmp_kata.write(h + i + h)
    cmp_kata.write('\n')
    cmp_kata.write(h + i + i)
    cmp_kata.write('\n')
    cmp_kata.write(h + i + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + j + a)
    cmp_kata.write('\n')
    cmp_kata.write(h + j + b)
    cmp_kata.write('\n')
    cmp_kata.write(h + j + c)
    cmp_kata.write('\n')
    cmp_kata.write(h + j + d)
    cmp_kata.write('\n')
    cmp_kata.write(h + j + e)
    cmp_kata.write('\n')
    cmp_kata.write(h + j + f)
    cmp_kata.write('\n')
    cmp_kata.write(h + j + g)
    cmp_kata.write('\n')
    cmp_kata.write(h + j + h)
    cmp_kata.write('\n')
    cmp_kata.write(h + j + i)
    cmp_kata.write('\n')
    cmp_kata.write(h + j + j)
    cmp_kata.write('\n')
    cmp_kata.write(i + a + a)
    cmp_kata.write('\n')
    cmp_kata.write(i + a + b)
    cmp_kata.write('\n')
    cmp_kata.write(i + a + c)
    cmp_kata.write('\n')
    cmp_kata.write(i + a + d)
    cmp_kata.write('\n')
    cmp_kata.write(i + a + e)
    cmp_kata.write('\n')
    cmp_kata.write(i + a + f)
    cmp_kata.write('\n')
    cmp_kata.write(i + a + g)
    cmp_kata.write('\n')
    cmp_kata.write(i + a + h)
    cmp_kata.write('\n')
    cmp_kata.write(i + a + i)
    cmp_kata.write('\n')
    cmp_kata.write(i + a + j)
    cmp_kata.write('\n')
    cmp_kata.write(i + b + a)
    cmp_kata.write('\n')
    cmp_kata.write(i + b + b)
    cmp_kata.write('\n')
    cmp_kata.write(i + b + c)
    cmp_kata.write('\n')
    cmp_kata.write(i + b + d)
    cmp_kata.write('\n')
    cmp_kata.write(i + b + e)
    cmp_kata.write('\n')
    cmp_kata.write(i + b + f)
    cmp_kata.write('\n')
    cmp_kata.write(i + b + g)
    cmp_kata.write('\n')
    cmp_kata.write(i + b + h)
    cmp_kata.write('\n')
    cmp_kata.write(i + b + i)
    cmp_kata.write('\n')
    cmp_kata.write(i + b + j)
    cmp_kata.write('\n')
    cmp_kata.write(i + c + a)
    cmp_kata.write('\n')
    cmp_kata.write(i + c + b)
    cmp_kata.write('\n')
    cmp_kata.write(i + c + c)
    cmp_kata.write('\n')
    cmp_kata.write(i + c + d)
    cmp_kata.write('\n')
    cmp_kata.write(i + c + e)
    cmp_kata.write('\n')
    cmp_kata.write(i + c + f)
    cmp_kata.write('\n')
    cmp_kata.write(i + c + g)
    cmp_kata.write('\n')
    cmp_kata.write(i + c + h)
    cmp_kata.write('\n')
    cmp_kata.write(i + c + i)
    cmp_kata.write('\n')
    cmp_kata.write(i + c + j)
    cmp_kata.write('\n')
    cmp_kata.write(i + d + a)
    cmp_kata.write('\n')
    cmp_kata.write(i + d + b)
    cmp_kata.write('\n')
    cmp_kata.write(i + d + c)
    cmp_kata.write('\n')
    cmp_kata.write(i + d + d)
    cmp_kata.write('\n')
    cmp_kata.write(i + d + e)
    cmp_kata.write('\n')
    cmp_kata.write(i + d + f)
    cmp_kata.write('\n')
    cmp_kata.write(i + d + g)
    cmp_kata.write('\n')
    cmp_kata.write(i + d + h)
    cmp_kata.write('\n')
    cmp_kata.write(i + d + i)
    cmp_kata.write('\n')
    cmp_kata.write(i + d + j)
    cmp_kata.write('\n')
    cmp_kata.write(i + e + a)
    cmp_kata.write('\n')
    cmp_kata.write(i + e + b)
    cmp_kata.write('\n')
    cmp_kata.write(i + e + c)
    cmp_kata.write('\n')
    cmp_kata.write(i + e + d)
    cmp_kata.write('\n')
    cmp_kata.write(i + e + e)
    cmp_kata.write('\n')
    cmp_kata.write(i + e + f)
    cmp_kata.write('\n')
    cmp_kata.write(i + e + g)
    cmp_kata.write('\n')
    cmp_kata.write(i + e + h)
    cmp_kata.write('\n')
    cmp_kata.write(i + e + i)
    cmp_kata.write('\n')
    cmp_kata.write(i + e + j)
    cmp_kata.write('\n')
    cmp_kata.write(i + f + a)
    cmp_kata.write('\n')
    cmp_kata.write(i + f + b)
    cmp_kata.write('\n')
    cmp_kata.write(i + f + c)
    cmp_kata.write('\n')
    cmp_kata.write(i + f + d)
    cmp_kata.write('\n')
    cmp_kata.write(i + f + e)
    cmp_kata.write('\n')
    cmp_kata.write(i + f + f)
    cmp_kata.write('\n')
    cmp_kata.write(i + f + g)
    cmp_kata.write('\n')
    cmp_kata.write(i + f + h)
    cmp_kata.write('\n')
    cmp_kata.write(i + f + i)
    cmp_kata.write('\n')
    cmp_kata.write(i + f + j)
    cmp_kata.write('\n')
    cmp_kata.write(i + g + a)
    cmp_kata.write('\n')
    cmp_kata.write(i + g + b)
    cmp_kata.write('\n')
    cmp_kata.write(i + g + c)
    cmp_kata.write('\n')
    cmp_kata.write(i + g + d)
    cmp_kata.write('\n')
    cmp_kata.write(i + g + e)
    cmp_kata.write('\n')
    cmp_kata.write(i + g + f)
    cmp_kata.write('\n')
    cmp_kata.write(i + g + g)
    cmp_kata.write('\n')
    cmp_kata.write(i + g + h)
    cmp_kata.write('\n')
    cmp_kata.write(i + g + i)
    cmp_kata.write('\n')
    cmp_kata.write(i + g + j)
    cmp_kata.write('\n')
    cmp_kata.write(i + h + a)
    cmp_kata.write('\n')
    cmp_kata.write(i + h + b)
    cmp_kata.write('\n')
    cmp_kata.write(i + h + c)
    cmp_kata.write('\n')
    cmp_kata.write(i + h + d)
    cmp_kata.write('\n')
    cmp_kata.write(i + h + e)
    cmp_kata.write('\n')
    cmp_kata.write(i + h + f)
    cmp_kata.write('\n')
    cmp_kata.write(i + h + g)
    cmp_kata.write('\n')
    cmp_kata.write(i + h + h)
    cmp_kata.write('\n')
    cmp_kata.write(i + h + i)
    cmp_kata.write('\n')
    cmp_kata.write(i + h + j)
    cmp_kata.write('\n')
    cmp_kata.write(i + i + a)
    cmp_kata.write('\n')
    cmp_kata.write(i + i + b)
    cmp_kata.write('\n')
    cmp_kata.write(i + i + c)
    cmp_kata.write('\n')
    cmp_kata.write(i + i + d)
    cmp_kata.write('\n')
    cmp_kata.write(i + i + e)
    cmp_kata.write('\n')
    cmp_kata.write(i + i + f)
    cmp_kata.write('\n')
    cmp_kata.write(i + i + g)
    cmp_kata.write('\n')
    cmp_kata.write(i + i + h)
    cmp_kata.write('\n')
    cmp_kata.write(i + i + i)
    cmp_kata.write('\n')
    cmp_kata.write(i + i + j)
    cmp_kata.write('\n')
    cmp_kata.write(i + j + a)
    cmp_kata.write('\n')
    cmp_kata.write(i + j + b)
    cmp_kata.write('\n')
    cmp_kata.write(i + j + c)
    cmp_kata.write('\n')
    cmp_kata.write(i + j + d)
    cmp_kata.write('\n')
    cmp_kata.write(i + j + e)
    cmp_kata.write('\n')
    cmp_kata.write(i + j + f)
    cmp_kata.write('\n')
    cmp_kata.write(i + j + g)
    cmp_kata.write('\n')
    cmp_kata.write(i + j + h)
    cmp_kata.write('\n')
    cmp_kata.write(i + j + i)
    cmp_kata.write('\n')
    cmp_kata.write(i + j + j)
    cmp_kata.write('\n')
    cmp_kata.write(j + a + b)
    cmp_kata.write('\n')
    cmp_kata.write(j + a + c)
    cmp_kata.write('\n')
    cmp_kata.write(j + a + d)
    cmp_kata.write('\n')
    cmp_kata.write(j + a + e)
    cmp_kata.write('\n')
    cmp_kata.write(j + a + f)
    cmp_kata.write('\n')
    cmp_kata.write(j + a + g)
    cmp_kata.write('\n')
    cmp_kata.write(j + a + h)
    cmp_kata.write('\n')
    cmp_kata.write(j + a + i)
    cmp_kata.write('\n')
    cmp_kata.write(j + a + j)
    cmp_kata.write('\n')
    cmp_kata.write(j + b + a)
    cmp_kata.write('\n')
    cmp_kata.write(j + b + b)
    cmp_kata.write('\n')
    cmp_kata.write(j + b + c)
    cmp_kata.write('\n')
    cmp_kata.write(j + b + d)
    cmp_kata.write('\n')
    cmp_kata.write(j + b + e)
    cmp_kata.write('\n')
    cmp_kata.write(j + b + f)
    cmp_kata.write('\n')
    cmp_kata.write(j + b + g)
    cmp_kata.write('\n')
    cmp_kata.write(j + b + h)
    cmp_kata.write('\n')
    cmp_kata.write(j + b + i)
    cmp_kata.write('\n')
    cmp_kata.write(j + b + j)
    cmp_kata.write('\n')
    cmp_kata.write(j + c + a)
    cmp_kata.write('\n')
    cmp_kata.write(j + c + b)
    cmp_kata.write('\n')
    cmp_kata.write(j + c + c)
    cmp_kata.write('\n')
    cmp_kata.write(j + c + d)
    cmp_kata.write('\n')
    cmp_kata.write(j + c + e)
    cmp_kata.write('\n')
    cmp_kata.write(j + c + f)
    cmp_kata.write('\n')
    cmp_kata.write(j + c + g)
    cmp_kata.write('\n')
    cmp_kata.write(j + c + h)
    cmp_kata.write('\n')
    cmp_kata.write(j + c + i)
    cmp_kata.write('\n')
    cmp_kata.write(j + c + j)
    cmp_kata.write('\n')
    cmp_kata.write(j + d + a)
    cmp_kata.write('\n')
    cmp_kata.write(j + d + b)
    cmp_kata.write('\n')
    cmp_kata.write(j + d + c)
    cmp_kata.write('\n')
    cmp_kata.write(j + d + d)
    cmp_kata.write('\n')
    cmp_kata.write(j + d + e)
    cmp_kata.write('\n')
    cmp_kata.write(j + d + f)
    cmp_kata.write('\n')
    cmp_kata.write(j + d + g)
    cmp_kata.write('\n')
    cmp_kata.write(j + d + h)
    cmp_kata.write('\n')
    cmp_kata.write(j + d + i)
    cmp_kata.write('\n')
    cmp_kata.write(j + d + j)
    cmp_kata.write('\n')
    cmp_kata.write(j + e + a)
    cmp_kata.write('\n')
    cmp_kata.write(j + e + b)
    cmp_kata.write('\n')
    cmp_kata.write(j + e + c)
    cmp_kata.write('\n')
    cmp_kata.write(j + e + d)
    cmp_kata.write('\n')
    cmp_kata.write(j + e + e)
    cmp_kata.write('\n')
    cmp_kata.write(j + e + f)
    cmp_kata.write('\n')
    cmp_kata.write(j + e + g)
    cmp_kata.write('\n')
    cmp_kata.write(j + e + h)
    cmp_kata.write('\n')
    cmp_kata.write(j + e + i)
    cmp_kata.write('\n')
    cmp_kata.write(j + e + j)
    cmp_kata.write('\n')
    cmp_kata.write(j + f + a)
    cmp_kata.write('\n')
    cmp_kata.write(j + f + b)
    cmp_kata.write('\n')
    cmp_kata.write(j + f + c)
    cmp_kata.write('\n')
    cmp_kata.write(j + f + d)
    cmp_kata.write('\n')
    cmp_kata.write(j + f + e)
    cmp_kata.write('\n')
    cmp_kata.write(j + f + f)
    cmp_kata.write('\n')
    cmp_kata.write(j + f + g)
    cmp_kata.write('\n')
    cmp_kata.write(j + f + h)
    cmp_kata.write('\n')
    cmp_kata.write(j + f + i)
    cmp_kata.write('\n')
    cmp_kata.write(j + f + j)
    cmp_kata.write('\n')
    cmp_kata.write(j + g + a)
    cmp_kata.write('\n')
    cmp_kata.write(j + g + b)
    cmp_kata.write('\n')
    cmp_kata.write(j + g + c)
    cmp_kata.write('\n')
    cmp_kata.write(j + g + d)
    cmp_kata.write('\n')
    cmp_kata.write(j + g + e)
    cmp_kata.write('\n')
    cmp_kata.write(j + g + f)
    cmp_kata.write('\n')
    cmp_kata.write(j + g + g)
    cmp_kata.write('\n')
    cmp_kata.write(j + g + h)
    cmp_kata.write('\n')
    cmp_kata.write(j + g + i)
    cmp_kata.write('\n')
    cmp_kata.write(j + g + j)
    cmp_kata.write('\n')
    cmp_kata.write(j + h + a)
    cmp_kata.write('\n')
    cmp_kata.write(j + h + b)
    cmp_kata.write('\n')
    cmp_kata.write(j + h + c)
    cmp_kata.write('\n')
    cmp_kata.write(j + h + d)
    cmp_kata.write('\n')
    cmp_kata.write(j + h + e)
    cmp_kata.write('\n')
    cmp_kata.write(j + h + f)
    cmp_kata.write('\n')
    cmp_kata.write(j + h + g)
    cmp_kata.write('\n')
    cmp_kata.write(j + h + h)
    cmp_kata.write('\n')
    cmp_kata.write(j + h + i)
    cmp_kata.write('\n')
    cmp_kata.write(j + h + j)
    cmp_kata.write('\n')
    cmp_kata.write(j + i + a)
    cmp_kata.write('\n')
    cmp_kata.write(j + i + b)
    cmp_kata.write('\n')
    cmp_kata.write(j + i + c)
    cmp_kata.write('\n')
    cmp_kata.write(j + i + d)
    cmp_kata.write('\n')
    cmp_kata.write(j + i + e)
    cmp_kata.write('\n')
    cmp_kata.write(j + i + f)
    cmp_kata.write('\n')
    cmp_kata.write(j + i + g)
    cmp_kata.write('\n')
    cmp_kata.write(j + i + h)
    cmp_kata.write('\n')
    cmp_kata.write(j + i + i)
    cmp_kata.write('\n')
    cmp_kata.write(j + i + j)
    cmp_kata.write('\n')
    cmp_kata.write(j + j + a)
    cmp_kata.write('\n')
    cmp_kata.write(j + j + b)
    cmp_kata.write('\n')
    cmp_kata.write(j + j + c)
    cmp_kata.write('\n')
    cmp_kata.write(j + j + d)
    cmp_kata.write('\n')
    cmp_kata.write(j + j + e)
    cmp_kata.write('\n')
    cmp_kata.write(j + j + f)
    cmp_kata.write('\n')
    cmp_kata.write(j + j + g)
    cmp_kata.write('\n')
    cmp_kata.write(j + j + h)
    cmp_kata.write('\n')
    cmp_kata.write(j + j + i)
    cmp_kata.write('\n')
    cmp_kata.write(j + j + j)
    cmp_kata.write('\n')
    cmp_kata.write(g + i + j)
    cmp_kata.write('\n')
    cmp_kata.write(h + i + j)
    cmp_kata.write('\n')
    extra_words = raw_input('[+] Would you like to add the 25 most popular passwords to your list? [y or n] : ')
    if extra_words == "y":
        cmp_kata = open(name_file + '.txt','a+')
        cmp_kata.write('123456')
        cmp_kata.write('\n')
        cmp_kata.write('123456789')
        cmp_kata.write('\n')
        cmp_kata.write('qwerty')
        cmp_kata.write('\n')
        cmp_kata.write('12345678')
        cmp_kata.write('\n')
        cmp_kata.write('111111')
        cmp_kata.write('\n')
        cmp_kata.write('1234567890')
        cmp_kata.write('\n')
        cmp_kata.write('1234567')
        cmp_kata.write('\n')
        cmp_kata.write('password')
        cmp_kata.write('\n')
        cmp_kata.write('123123')
        cmp_kata.write('\n')
        cmp_kata.write('987654321')
        cmp_kata.write('\n')
        cmp_kata.write('qwertyuiop')
        cmp_kata.write('\n')
        cmp_kata.write('mynoob')
        cmp_kata.write('\n')
        cmp_kata.write('123321')
        cmp_kata.write('\n')
        cmp_kata.write('666666')
        cmp_kata.write('\n')
        cmp_kata.write('18atcskd2w')
        cmp_kata.write('\n')
        cmp_kata.write('7777777')
        cmp_kata.write('\n')
        cmp_kata.write('1q2w3e4r')
        cmp_kata.write('\n')
        cmp_kata.write('654321')
        cmp_kata.write('\n')
        cmp_kata.write('555555')
        cmp_kata.write('\n')
        cmp_kata.write('3rjs1la7qe')
        cmp_kata.write('\n')
        cmp_kata.write('google')
        cmp_kata.write('\n')
        cmp_kata.write('1q2w3e4r5t')
        cmp_kata.write('\n')
        cmp_kata.write('123qwe')
        cmp_kata.write('\n')
        cmp_kata.write('zxcvbnm')
        cmp_kata.write('\n')
        cmp_kata.write('1q2w3e')
        cmp_kata.write('\n')
        print ("\n[+] Added!\n")
        cmp_kata.close()
    else:
        print ("\n[-] Okay!\n")
        cmp_kata.close()
    random_numbers = raw_input('[+] Would you like to add random numbers to your list? [y or n] : ')
    if random_numbers == "y":
        cmp_kata = open(name_file + '.txt','a+')
        cmp_kata.write(str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)))
        cmp_kata.write('\n')
        cmp_kata.write(str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)))
        cmp_kata.write('\n')
        cmp_kata.write(str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)))
        cmp_kata.write('\n')
        cmp_kata.write(str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)))
        cmp_kata.write('\n')
        cmp_kata.write(str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)))
        cmp_kata.write('\n')
        cmp_kata.write(str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)) + str(randint(0,9)))
        cmp_kata.write('\n')
        cmp_kata.close()
        print ("\n[+] Added!\n")
    else:
        print ("\n[-] Okay!\n")
        cmp_kata.close()

        ### And ends here ###
    print("\t\nSaved to : " + name_file + ".txt")
    print("Now load your canon and shoot with " + name_file + ".txt!")
except KeyboardInterrupt:
    webbrowser.open('https://www.instagram.com/_t0x1c/')
